### ISSUE TITLE
(API) Practicing CRUD operation using FastApi along with MongoDB

### ISSUE THREAD

**Issue by mjayakumarmca** [thinkarlabs/P23-003-MalnutritionDashboard#10]
-  learn basics of FastApi with python and try to use Mongodb Atlas cluster online

**Comment by AlekhyaArasavalli** [comment]
Some of the Urls:

- https://www.fastapitutorial.com/blog/fastapi-course/

-  https://fastapi.tiangolo.com/features/

- https://testdriven.io/blog/fastapi-mongo/

- https://github.com/Princekrampah/fastAPIDocker/tree/master/fastAPIMongoDB_todoAPP
