### ISSUE TITLE
(UI) Explore the Cypress automation for VueJS

### ISSUE THREAD

**Issue by mjayakumarmca** [thinkarlabs/P23-003-MalnutritionDashboard#114]
Need to explore the possible implementation flow for a single simple page with cypress automation

**Comment by 786ahmedhussain** [comment]
https://blog.logrocket.com/unit-testing-react-cypress/

**Comment by 786ahmedhussain** [comment]
https://www.sitepoint.com/cypress-testing/

**Comment by 786ahmedhussain** [comment]
github references

**Comment by 786ahmedhussain** [comment]
https://example.cypress.io/commands/querying
