### ISSUE TITLE
(API) Create separate routes for Supplement details  and supplement packs

### ISSUE THREAD

**Issue by mjayakumarmca** [thinkarlabs/P23-003-MalnutritionDashboard#125]
**Current problem:**

All the routes are in single routes.py file.

**Proposed solution:**

Create a separate route for Supplement packs and supplement details as separate route with "filename.py" under routes folder for backend.

All the Endpoints for Supplement packs and supplement details should work as it is.**

**Comment by AlekhyaArasavalli** [comment]
1.added routes for Supplement packs
2.added routes for Supplement details
#127
