### ISSUE TITLE
(API) Implement the User Addition

### ISSUE THREAD

**Issue by mjayakumarmca** [thinkarlabs/P23-003-MalnutritionDashboard#17]
**Description:**

1. Create the User Model
2. Make sure that we have a flag to differentiate the user is of Admin/NGO/Aganwadi
3. Create a Get request to validate the login user from Mongodb 

Note:
  If prior table it not needed NoSQL MongoDB then this story holds good otherwise create one and proceed.

**Comment by AlekhyaArasavalli** [comment]
has added user addition and made get call for login
