### ISSUE TITLE
(API) Supplement Distribution

### ISSUE THREAD

**Issue by mjayakumarmca** [thinkarlabs/P23-003-MalnutritionDashboard#57]
User should be able to supplementary given details

1) SupplementaryID(Foreign key to original table)
2) GivenDate
3) No of packs given

these 3 columns needs to be captured in the DB with CRUD REST API

Reference Mock:

![Image](https://user-images.githubusercontent.com/6660580/222401608-f401a826-9f82-4a71-8c17-27421d3ee0e4.png)

**Comment by AlekhyaArasavalli** [comment]
https://github.com/thinkarlabs/P23-003-MalnutritionDashboard/pull/64
