### ISSUE TITLE
(API) Setting up MongoDB & Exploring it

### ISSUE THREAD

**Issue by mjayakumarmca** [thinkarlabs/P23-003-MalnutritionDashboard#9]

**Comment by AlekhyaArasavalli** [comment]
Try to create an account & connect with cluster 
Try to connect with fastApi & Mongodb Atlas

-   Ref:
https://www.mongodb.com/languages/python/pymongo-tutorial
https://www.mongodb.com/developer/languages/python/python-quickstart-fastapi/
